EXECUTABLE := cufft_3d_c2c_scalable
CUFILES := cufft_3d_c2c_scalable.cu
CCFILES :=
ADDITIONAL_LIBS := -lcufft
OMIT_CUTIL_LIB := 1
OMIT_SHRUTIL_LIB := 1
SM_VERSIONS := 75 80 90

include ../../../common/common.mk
