EXECUTABLE := cufft_lto_r2c_c2r_scalable
CUFILES :=
CCFILES := cufft_lto_r2c_c2r_scalable.cpp
ADDITIONAL_LIBS := -lcufft
OMIT_CUTIL_LIB := 1
OMIT_SHRUTIL_LIB := 1
SM_VERSIONS := 75 80 90

include ../../../common/common.mk
