#!/bin/sh

ORIGINAL_FOLDER=$PWD
BASE_MLPERF_DIR=$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/mlperf_inference/
cd $BASE_MLPERF_DIR
. ./mlc/bin/activate
mlcr install,python-venv --name=mlperf &&
export MLC_SCRIPT_EXTRA_CMD="--adr.python.name=mlperf" &&
mlcr run-mlperf,inference,_full,_r5.0-dev \
   --model=bert-99 \
   --implementation=reference \
   --framework=pytorch \
   --category=edge \
   --scenario=Offline \
   --execution_mode=valid \
   --device=cuda \
   --quiet 
deactivate
cd $ORIGINAL_FOLDER
