EXECUTABLE := cusolver_ormqr_scalable
CUFILES := cusolver_ormqr_scalable.cu
CCFILES :=
ADDITIONAL_LIBS := -lcusolver -lcublas
OMIT_CUTIL_LIB := 1
OMIT_SHRUTIL_LIB := 1
SM_VERSIONS := 75 80 90

include ../../../common/common.mk
