name: Test Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the mydev branch
  push:
    branches-ignore:
      - "gh-readonly-queue**"
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  test-12-8:
    env:
      CUDA_INSTALL_PATH: /usr/local/cuda 
      BOOST_ROOT: /usr/include/boost
    runs-on: ubuntu-latest
    container:
     image: nvidia/cuda:13.1.1-cudnn-devel-ubuntu24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install dependencies
        run: |
              apt-get update && apt-get install -y git build-essential cmake libboost-all-dev wget
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: false  # This clones submodules
      
      - name: Build Apps
        run: |
             git config --global --add safe.directory /__w/gpu-app-collection/gpu-app-collection
             git submodule update --init -- src/cuda/cuda-samples
             git submodule update --init -- src/cuda/cutlass-bench
             /bin/bash test-build.sh ci

      - name: Print Successful Apps
        if: always()
        run: |
              echo "Built $(ls bin/*/release | wc -l) Apps:"
              ls bin/*/release
